Turtlebot Tutorial update
lulav/citros_doc pull request #100
Opened 2023-12-15 11:27 UTC by gtep96

Requesting review

2023-12-17 10:24 UTC, mariaBer requested changes

2023-12-17 10:24 UTC, mariaBer commented on docs_tutorials/turtlebot/turtlebot.md
>  As you can see, the travelled trajectory varies for different sids:
what is sids?

2023-12-17 11:38 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
>  ![png](img/turtlebot3_0.png "TurtleBot3")
Done

2023-12-17 11:39 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
>  # TurtleBot3 Example Using CITROS
Done

2023-12-17 11:39 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +4. (Optional) Install [FoxGlove](https://docs.foxglove.dev/docs/introduction).
Done

2023-12-17 11:40 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +This project contains two launch files, but we will use only ```turtlebot3_sim_cont.launch.py```, and the second one launches automatically (it's necessary for publishing states).
Yes

2023-12-17 11:44 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +The ROS 2 node interfaces with the official TurtleBot3 simulation example, leveraging the TurtleBot3 robot model and simulated environment. This integration allows users to observe how the robot beha
ROS 2 Node uses Turtlebot3 simulation with Autonomous Collision Avoidance module connected. Robot drives in the `room` (named turtlebot_world) avoiding obstacles using sensors (e.g. lidars).

2023-12-17 11:45 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +For this example, let's check how the powerfull CITROS Error Analysis (a part of Data Analysis) package works. To do it out, we need to set up parameters and launch CITROS simulation.<br/>
Deleted the first one

2023-12-17 11:53 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +For this example, let's check how the powerfull CITROS Error Analysis (a part of Data Analysis) package works. To do it out, we need to set up parameters and launch CITROS simulation.<br/>
As I said, this project doesn't do any research, it was created to show the ability of implementing and using very popular robotic lib Turtlebot to CITROS. In addition, i've added some exapmles of Data Analysis usage to the Notebook. So, the main purpuse of this project is to show the ability to implement the Turtlebot lib to CITROS and to work and to analyse its data. And the secondary is to show some advantages of Data Analysis package. Basicly, this was the main task for all the tutorials - show to the user the ability to work with popular and complex robotic/scientific libs with CITROS.

2023-12-17 11:54 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +All the results will be saved under .citros/runs/[simulation_name] [folder].
Done

2023-12-17 11:57 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
>  Select the launch file by pressing ```Enter``` button and wait for the output in the terminal. To plot the local run results you can use FoxGlove.
Done

2023-12-17 11:58 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +To plot the local run results you can use [FoxGlove](https://citros.io/doc/docs_tutorials/#visualization-with-foxglove).
added

2023-12-17 12:00 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
>  As you can see, the travelled trajectory varies for different sids:
done, used simulations insted of sids. Should be more clear now

2023-12-17 12:02 UTC, gtep96 commented
@mariaBer changes pushed

2023-12-18 11:01 UTC, mariaBer requested changes

2023-12-18 11:59 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +This project contains two launch files, but we will use only ```turtlebot3_sim_cont.launch.py```, and the second one launches automatically (it's necessary for publishing states).
Done

2023-12-18 12:00 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> + |turtlebot3_gazebo
fixed

2023-12-18 12:02 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +The ROS 2 node interfaces with the official TurtleBot3 simulation example, leveraging the TurtleBot3 robot model and simulated environment. This integration allows users to observe how the robot beha
Done

2023-12-18 12:25 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +The default setup is 600 seconds timeout, 4 CPU, 4 GPU and 4096 MB of Memory.
fixed

2023-12-18 13:48 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +To plot the local run results you can use [Foxglove](https://citros.io/doc/docs_tutorials/#visualization-with-foxglove) with the ```layout.json``` layout that exists in the ```Foxglove_layouts``` dir
done

2023-12-19 10:21 UTC, gtep96 commented
@mariaBer i've updated the tutorial, but not is the scenario description clear enough now, just wanted to discuss it with you. anyway you can check it

2023-12-20 12:29 UTC, gtep96 commented
updated and pushed

2023-12-20 17:59 UTC, mariaBer requested changes

2023-12-20 17:59 UTC, mariaBer commented on docs_tutorials/turtlebot/turtlebot.md
> +The project gives users the flexibility to modify various TurtleBot3 specifications by changing ROS 2 parameters. These parameters may include attributes like the robot's size, speed, sensor range, o
This part until for this example should not be here

2023-12-20 17:59 UTC, mariaBer commented on docs_tutorials/turtlebot/turtlebot.md
> +The parameter setup is listed in ```.citros/parameter_setups/default_param_setup.json```:
In this tutorial, we will examine the powerful CITROS Error Analysis (a part of Data Analysis) package. We will analyze data from IMU (Inertial Measurement Unit), Odometer and position information. For that, we need to set up parameters and launch CITROS simulation. The parameter setup is listed in .citros/parameter_setups/default_param_setup.json:

2023-12-21 09:20 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +The project gives users the flexibility to modify various TurtleBot3 specifications by changing ROS 2 parameters. These parameters may include attributes like the robot's size, speed, sensor range, o
Done

2023-12-21 09:21 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
> +The parameter setup is listed in ```.citros/parameter_setups/default_param_setup.json```:
Done

2023-12-21 09:21 UTC, gtep96 commented
Done and pushed

2023-12-21 11:02 UTC, mariaBer requested changes

2023-12-21 11:02 UTC, mariaBer commented on docs_tutorials/turtlebot/turtlebot.md
>  This project is designed to wrap the official [TurtleBot3 simulation example](https://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/#gazebo-simulation) and integrate it with a simple Aut
Is this part needed if you added the section below?
The node provides ROS 2 parameters that allow users to adjust various TurtleBot3 specifications, enabling the analysis of how these changes affect collision avoidance behavior. <br />

2023-12-21 11:12 UTC, gtep96 commented on docs_tutorials/turtlebot/turtlebot.md
>  This project is designed to wrap the official [TurtleBot3 simulation example](https://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/#gazebo-simulation) and integrate it with a simple Aut
I think it's possible to delete the sentence "The node provides ROS 2 parameters that allow users to adjust various TurtleBot3 specifications, enabling the analysis of how these changes affect collision avoidance behavior." Done

2023-12-21 11:18 UTC, mariaBer approved these changes

2023-12-21 11:18 UTC, merged