Poliastro tutorial update
lulav/citros_doc pull request #101
Opened 2023-12-18 11:32 UTC by gtep96

2023-12-19 08:28 UTC, mariaBer requested changes

2023-12-19 08:28 UTC, mariaBer commented on docs_tutorials/poliastro/poliastro.md
> +Finally, we can run the simulation in the cloud! Simply add `-r` to the terminal command:
Finally, we can run the simulation in the cloud.<br />
We will run the simulation 10 times by adding `-c 10` to the command and run it in the CITROS server by adding `-r` to the command:

2023-12-19 10:44 UTC, gtep96 commented on docs_tutorials/poliastro/poliastro.md
> +In this tutorial we will use the Atmospheric Drag simulation scenario (as one of the most interesting :).<br/>
Done

2023-12-19 10:46 UTC, gtep96 commented on docs_tutorials/poliastro/poliastro.md
> +This parameters can be found in ```.citros/simulations/simulation_poliastro.json```. <br/>
Done

2023-12-19 10:47 UTC, gtep96 commented on docs_tutorials/poliastro/poliastro.md
> +The default setup is 180 seconds timeout, 2 CPU, 2 GPU and 2048 MB of Memory.
Done

2023-12-19 10:48 UTC, gtep96 commented
@mariaBer done and pushed

2023-12-19 18:31 UTC, mariaBer commented on docs_tutorials/poliastro/poliastro.md
> +To find out how the exact orbit duration will reduce, we need to launch a batch with several simulations and a distribution Drag Coefficient parameter, it will be set by a NumPy random function:
I don't understand why you keept this part. please explain

2023-12-19 18:37 UTC, mariaBer commented on docs_tutorials/poliastro/poliastro.md
> +The default setup is 180 seconds timeout, 2 CPU, 2 GPU and 2048 MB of Memory.
What am I missing?

<img width="459" alt="image" src="https://github.com/lulav/citros_doc/assets/23418333/59415acf-5402-4dc7-9d4e-d5587496f036">

2023-12-20 07:31 UTC, mariaBer commented on docs_tutorials/poliastro/poliastro.md
> +The default setup is 180 seconds timeout, 2 CPU, 2 GPU and 2048 MB of Memory.
I don't really understand what I need to ask Vova.
The above is a screenshot of the json file. 
You wrote in the text file: "The **default** setup is 180 seconds timeout, 2 CPU, 2 GPU and 2048 MB of Memory."
This is not what's written in this json. this should be fixed.

2023-12-20 10:59 UTC, mariaBer requested changes

2023-12-20 10:59 UTC, mariaBer commented on docs_tutorials/poliastro/poliastro.md
> +Drag forces calculations are more difficult and more rare than the others, hence, in this tutorial we will use the Atmospheric Drag simulation scenario. <br />
See if this can replace it: 

Drag forces calculations are more difficult and more rare than the others, hence, in this tutorial we will use the Atmospheric Drag simulation scenario. <br />
Let's check how the exact orbit duration reduces depending on Drag coefficient. For that, we will set up Drag Coefficient (```c_d```) parameter random distribution in range from 2 to 4. <br />
The parameter will be set by a NumPy random function and its setup is listed in `.citros/parameter_setups/default_param_setup.json`.

2023-12-20 12:08 UTC, gtep96 commented on docs_tutorials/poliastro/poliastro.md
> +Drag forces calculations are more difficult and more rare than the others, hence, in this tutorial we will use the Atmospheric Drag simulation scenario. <br />
Done

2023-12-20 12:08 UTC, gtep96 commented
updated and pushed

2023-12-20 17:27 UTC, merged