docs(docs_data_analysis): update and improvements
lulav/citros_doc pull request #49
Opened 2023-10-23 18:10 UTC by Yalyalieva

version v0.7.0 and improvements

2023-10-28 12:40 UTC, Yalyalieva commented
I added snippets in the form as they are in citros web.

2023-10-28 12:42 UTC, Yalyalieva commented on docs_data_analysis/data_access/index.md
fixed

2023-10-28 12:43 UTC, Yalyalieva commented on docs_data_analysis_versioned_docs/version-v0.7.0/documentation/error_analysis/citros_data_array.md
> +---
now parameters are in the tables

2023-10-28 15:21 UTC, mariaBer commented
@Yalyalieva Please capitalize fields names in tables

**As for new additions** - they should be added in a different PR, since these should be examined as well, however they should not hold the updates we are working on this past week.
Either add them in a new branch in a totally different PR or revert, stage the changes until this last PR will be finally approved

2023-10-28 15:30 UTC, Yalyalieva commented
@mariaBer new additions - you mean snippets? They were in the structure schema that you provided me. You want me to delete them?

2023-10-28 15:38 UTC, mariaBer commented
I added the final structure we should have. since we had a lot of conversations about it and wanter to summarize it.

Yes, I mean remove both Snippets and installation for THIS PR.
You can add the snippets as a place holder without the content inside,  but I don't want to hold off any updates in this structure.

The snippets and installation addition (and any new additions in the future should be added as a different PR,  in an updated branch)

2023-10-28 15:40 UTC, Yalyalieva commented
Which installations?

2023-10-28 15:51 UTC, mariaBer commented
the one added in the main page

Basically, this PR is to examine the same thing we examined passed week.
any new additions should be added in a different PR (and in an updated branch)

2023-10-28 20:55 UTC, mariaBer requested changes
@Yalyalieva 

- [ ] First title should be # 
- [ ] All Table fields should be capitalized

2023-10-28 20:55 UTC, mariaBer commented on docs_data_analysis/documentation/data_access/citros_dict.md
Capitalize fields names in tables - relevant to all tables throughout the docs

2023-10-28 20:55 UTC, mariaBer commented on docs_data_analysis/data_access/index.md
> +## Data access
First title should be #

2023-10-28 20:55 UTC, mariaBer commented on docs_data_analysis/documentation/data_access/references.md
> +## Class `Ref` {#citros_data_analysis.data_access.references.Ref}
First title should be #First title should be #

2023-10-28 20:55 UTC, mariaBer commented on docs_data_analysis/error_analysis/index.md
> +## Error analysis
First title should be #

2023-10-28 20:55 UTC, mariaBer commented on docs_data_analysis/index.md
> +## Data Analysis Overview
First title should be #

2023-10-28 20:55 UTC, mariaBer commented on docs_data_analysis/validation/index.md
> +## Validation
First title should be #

2023-10-28 23:24 UTC, Yalyalieva commented on docs_data_analysis/documentation/data_access/references.md
> +## Class `Ref` {#citros_data_analysis.data_access.references.Ref}
for documentation files that works in a bad way - in docusaurus the title with one '#' could not be used as references so the referenerce to the constructor of the class is missed. I make titles with one '#'. I can rename the constructors if you don't want the repetitions of the lines - for example from "Class `Ref`" to "Constructor `Ref`" (but it looks a little unusual for the documentation, the constructor usually goes with 'class' title) or change titles, for example "Documentation for the class Ref"

2023-10-28 23:25 UTC, Yalyalieva commented on docs_data_analysis/error_analysis/index.md
> +## Error analysis
+

2023-10-28 23:25 UTC, Yalyalieva commented on docs_data_analysis/index.md
> +## Data Analysis Overview
+

2023-10-28 23:25 UTC, Yalyalieva commented on docs_data_analysis/validation/index.md
> +## Validation
+

2023-10-28 23:25 UTC, Yalyalieva commented on docs_data_analysis/documentation/data_access/citros_dict.md
+

2023-10-28 23:27 UTC, Yalyalieva commented on docs_data_analysis/data_access/index.md
> +## Data access
done

2023-10-29 07:57 UTC, mariaBer commented on docs_data_analysis/documentation/data_access/references.md
> +## Class `Ref` {#citros_data_analysis.data_access.references.Ref}
What you did is OK, we have a title and we have the class itself.

2023-10-29 08:06 UTC, mariaBer requested changes

2023-10-29 08:06 UTC, mariaBer commented on docs_data_analysis/data_access/getting_started.md
> -## Data Access
Title should be as in sidebar

2023-10-29 08:06 UTC, mariaBer commented on docs_data_analysis/error_analysis/getting_started_query_data.md
> +# Error Analysis
Title should be as in sidebar

2023-10-29 08:06 UTC, mariaBer commented on docs_data_analysis/error_analysis/index.md
> +# Error analysis
Title should be as in sidebar

2023-10-29 08:06 UTC, mariaBer commented on docs_data_analysis/validation/getting_started.md
>  # Validation
Title should be as in sidebar

2023-10-29 08:06 UTC, mariaBer commented on docs_data_analysis/data_access/index.md
> +# Data access
Title should be as in sidebar

2023-10-29 08:08 UTC, mariaBer requested changes

2023-10-29 08:08 UTC, mariaBer commented on sidebarsDataAnalysis.js
>            label: 'Data access',
Capitalize

2023-10-29 08:08 UTC, mariaBer commented on sidebarsDataAnalysis.js
>            label: 'Error analysis',
Capitalize

2023-10-29 09:34 UTC, merged