docs(docs_data_analysis/index): add installation section
lulav/citros_doc pull request #60
Opened 2023-10-29 20:13 UTC by Yalyalieva

installation section + small fixes in documentation text

2023-10-29 21:25 UTC, mariaBer requested changes

2023-10-29 21:25 UTC, mariaBer commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
>  The package is devided into three modules: [Data access](data_access/index.md), [Error analysis](error_analysis/index.md) and [Validation](validation/index.md).
remove

2023-10-29 21:25 UTC, mariaBer commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
This package installed as part of  CITROS CLI.
To use the package you can either use it in CITROS.io or locally after installing and logging in with [CITROS CLI](/docs_cli/overview/cli_install).

2023-10-29 21:25 UTC, mariaBer commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
> +## Installation
Remove this part

2023-10-30 07:05 UTC, Yalyalieva commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
>  The package is devided into three modules: [Data access](data_access/index.md), [Error analysis](error_analysis/index.md) and [Validation](validation/index.md).
Why information about modules should be removed?

2023-10-30 07:06 UTC, Yalyalieva commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
> +## Installation
You mean to remove the title or the whole section?

2023-10-30 07:11 UTC, Yalyalieva commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
You want me to right it on the 9th line? It is important to stress that you not just working locally, but you still work with data from the cloud. In other tutorial by 'locally' means that you run simulations and got data locally, it is not the case

2023-10-30 07:23 UTC, mariaBer commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
> +## Installation
The text I added on top is a substitute for this part

2023-10-30 07:24 UTC, mariaBer commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
>  The package is devided into three modules: [Data access](data_access/index.md), [Error analysis](error_analysis/index.md) and [Validation](validation/index.md).
The TOC reflects the three modules

2023-10-30 07:52 UTC, mariaBer commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
Data analysis is a python package installed as part of CITROS CLI.
This gives you the ability to query and analyze data generated by CITROS. 
The package can be used either from citros.io python notebook located under each [repository notebook](/docs/repos/repository/repo_sc_code.md#directory-notebooks) or from local kernel python environment such as jupyter, VSC, etc.

2023-10-30 11:44 UTC, Yalyalieva commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
> +## Installation
But it is essential to write how to update the package. If the new version is released it is not updated, it is even not updated if you update citros. You can update it only if you remove citros and install it again or, what looks much better, when you update the package itself

2023-10-30 11:46 UTC, Yalyalieva commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
I still would like to add that it works with cloud data only

2023-10-30 15:52 UTC, mariaBer commented on docs_data_analysis_versioned_docs/version-v0.7.17/index.md
> +## Installation
Understood, however, no need to add it as an explanation. Its in fact an issue of CITROS CLI and should be fixed

2023-10-31 11:26 UTC, mariaBer commented
@Yalyalieva I'm running the branch and dont see the changes

2023-10-31 11:44 UTC, Yalyalieva commented
@mariaBer 
Sorry, forgot to transfer changes to the versioned document, they were only in 'next'

2023-10-31 12:25 UTC, mariaBer commented on docs_data_analysis/index.md
> +The package can be used either from [citros.io](https://citros.io/) python notebook located under each repository notebook or from local kernel python environment such as jupyter, VSC, etc. Iin the l
**citros_data_analysis** is a Python package that enables you to query and analyze data generated by running simulations in the CITROS cloud. This package can be used either from the citros.io Python notebook located under each [repository's notebook](docs/repos/repository/repo_sc_code#directory-notebooks) or from a local kernel Python environment such as Jupyter, VSC, etc., after installing the [CITROS](https://pypi.org/project/citros/) package and logging in.

The text above approved by Vova, if you have any questions/comment, discuss them with him

2023-10-31 16:12 UTC, merged