Doc/dockerfile
lulav/citros_doc pull request #63
Opened 2023-11-03 08:04 UTC by iftahnaf

adding Dockerfile documentation.

@vovacooper @shalevm @gtep96 @orrlulavspace  feel free to pull the branch and add more relevant information.

@mariaBer let's wait until Monday (6.11.2023) with your review on this, after getting feedback from the team.

2023-11-03 11:34 UTC, shalevm reviewed
i added a commit with some typo fixes.

2023-11-05 09:17 UTC, vovacooper requested changes

2023-11-05 09:17 UTC, vovacooper commented on docs/dockerfile/dockerfile_overview.md
> +RUN apt-get update && apt-get install -y ros-${ROS_DISTRO}-rosbag2-storage-mcap`
remove `

2023-11-05 09:17 UTC, vovacooper commented on docs/dockerfile/dockerfile_overview.md
> +6. **Run Tests**: Use the `docker run` command to locally run your simulation image, verifying the setup works before pushing the image to CITROS.
add the citros run full  command 

docker run {image name} citros run [simulation] ...

2023-11-05 09:17 UTC, vovacooper commented
@iftahnaf please add examples for docker files from our garden.

2023-11-06 06:44 UTC, iftahnaf commented
@vovacooper I fixed the comments, please review and approve.
@shalevm Thanks for the typos fixes, if there is no other issue please approve.
@gtep96 Please review and approve.
@orrlulavspace Please review and approve.

2023-11-06 07:10 UTC, vovacooper commented
@mariaBer 
<img width="1613" alt="image" src="https://github.com/lulav/citros_doc/assets/2060520/5e5bfa52-48d0-4bc4-9300-2a1c15bde862">
the table of content doesnt work. 
we have no table oc tontent on the right. 

<img width="405" alt="image" src="https://github.com/lulav/citros_doc/assets/2060520/46e0fb18-ff7e-469f-a6a2-c293a00838a9">
do we need a folder?

2023-11-06 07:14 UTC, iftahnaf commented
@vovacooper the TOC works in the markdown, Have you seen this issue before? (works in markdown and no work in the web)

2023-11-06 07:15 UTC, vovacooper commented
No, @mariaBer please check this

2023-11-06 07:51 UTC, mariaBer requested changes

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +#  Dockerfile Overview
Why " Dockerfile Overview" I think it should be more informative, "Dockerize CITROS" / "CITROS in Dockerfile"
or any other

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +# Table Of Contents
Links not working

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +When writing your Dockerfile, is it advised to build your ROS workspace in the Dockerfile.
...is it advised ....
it is advised

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +Once the upload of the docker image is done, you can check on CITROS [Image](https://citros.io/doc/docs/repos/repository/repo_sc_images) tab that the image exists.
send to citros.io/ image tab

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +2. **Install Required Packages:** Use the `RUN` instruction to install any necessary packages, libraries, and tools. You can also copy any custom scripts or configurations into the container.
Add link to website: https://docs.docker.com/engine/reference/builder/#run

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +3. **Set Environment Variables:** Use the `ENV` instruction to define environment variables that your application relies on. This ensures proper configuration within the container.
Add link to ENV

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +4. **Specify the Entry Point:** Use the `CMD` or `ENTRYPOINT` instruction to define the command that should be executed when the container starts. This is typically the command to run your CITROS sim
Add link to cmd, ENTRYPOINT

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
Only first title should have one #, all other should have ##, ###...
Change file name to be the same as the folder it has (this will remove the dropdown)

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +# Table Of Contents
## Table Of Contents

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +# About Dockerfiles
##

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +# Write Your Own Dockerfile
##

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +# Required Packages for CITROS Usage
##

2023-11-06 07:51 UTC, mariaBer commented on docs_tutorials/Dockerfile/dockerfile_overview.md
> +# Examples
##

2023-11-06 18:25 UTC, merged

2023-11-06 19:12 UTC, mariaBer commented
@iftahnaf I merged the branch to main by mistake so I'm fixing all issues I added in my review.

The issue with the ToC - it didnt work when running the branch, and it was since the titles where with only one #