docs(docs_data_analysis/snippets): examples of snippets
lulav/citros_doc pull request #65
Opened 2023-11-06 14:16 UTC by Yalyalieva

I'd like to show the code snippets. You can find them in the 'Next' version, just below the "CITROS Data Analysis" panel. There are two files: "Snippets like in web," which displays the snippets as they appear in Citros, and "Snippets," where I've removed the collapsed sections and added '#' to section titles to make right sidebar visibale. Please take a look and tell which variant is closer to how the snippets should be presented in documentation and what should be changed.

2023-11-07 07:57 UTC, mariaBer commented
@Yalyalieva, I'm running the branch and dont see the two options 
![image](https://github.com/lulav/citros_doc/assets/23418333/38a25b1d-1466-4ebe-8f5e-c070725a6fea)

2023-11-07 08:15 UTC, Yalyalieva commented
> @Yalyalieva, I'm running the branch and dont see the two options ![image](https://user-images.githubusercontent.com/23418333/280961393-38a25b1d-1466-4ebe-8f5e-c070725a6fea.png)

Please choose the version 'Next'. List of versions is on the top right

2023-11-07 08:32 UTC, mariaBer commented
@Yalyalieva Sorry, my bad.

It is definitely should look as the structure throughout CITROS Docs, hence the snippets option is more relevant, however, this is just too much info in one page, meaning it should be divided.

While we're adding a new section, please update the other sections structure as well.
Only Snippets will be under the "CITROS Data Analysis" drop-down, and all others will be in the same level as the drop-down 

![image](https://github.com/lulav/citros_doc/assets/23418333/987ef1b5-a744-483d-9320-b247b84184b8)

2023-11-08 12:41 UTC, mariaBer requested changes

2023-11-08 12:41 UTC, mariaBer commented on sidebarsDataAnalysis.js
Let's take snippets out as well, meaning that the first item wont be a drop down (like in citros web)

2023-11-08 12:41 UTC, mariaBer commented on docs_data_analysis/snippets_doc/snippets_data_analysis.md
Please divide this one into as much ## titles as you have so that data access will be a drop down and under it will be the sub-sections (repositories, users, batches, etc.)

2023-11-08 12:43 UTC, mariaBer commented
@Yalyalieva Besides the two comments, please update the ToC ass well

2023-11-11 08:07 UTC, merged