docs(drone-tutorial): update to the new scheme
lulav/citros_doc pull request #76
Opened 2023-11-14 12:55 UTC by iftahnaf

hi @mariaBer,

I update the drone tutorial according to the new template.

Please review.

2023-11-17 17:10 UTC, mariaBer requested changes

2023-11-17 17:10 UTC, mariaBer commented on docs_tutorials/drone/drone.md
The text below haven't change at tis commit but I think its worth update it as well:

- Finally, we run the simulation at the web:
1. Go to the `Repositories` page clicking on the tab on the top.
2. Find the drone project and open it.
3. Navigate to the `Runs` tab.
4. Click on the `Run Simulation` button on the right.

to:
1. Open [drone](https://citros.io/drone) project
2. Navigate to the `Runs` tab.
3. Click on the `Run Simulation` button on the right.

2023-11-17 17:10 UTC, mariaBer commented on docs_tutorials/drone/drone.md
Since getting started tutorial is not done, we might have a few more changes here.

2023-11-17 17:10 UTC, mariaBer commented on docs_tutorials/drone/drone.md
>  For our example, we will run the [scenario](#the-scenario) 50 times. Once the simulations are complete, we can create a notebook file located [here](https://citros.io/drone/blob/main/notebooks/wind_a
[scenario](#the-scenario) - link not working, change to #scenario

2023-11-19 11:27 UTC, iftahnaf commented on docs_tutorials/drone/drone.md
>  Then open the repository in VSCode's `devcontainer` with `reopen in container option`.
I don't think that it's needed. I want to keep it as minimal as possible, the screenshot can be added to the getting started tutorial as it will be needed for all CITROS tutorials.

2023-11-19 11:28 UTC, iftahnaf commented on docs_tutorials/drone/drone.md
> +[citros_cli](/docs_cli/configuration/config_params) provides more information about how to change the parameters by the user.
the project is called `citros_cli` in GitHub.  Let's call it like the project name in GitHub.

2023-11-19 11:28 UTC, iftahnaf commented on docs_tutorials/drone/drone.md
>  |     Variable     | Description | package |
yes, the packages are written in small letters in the workspace.

2023-11-19 11:29 UTC, iftahnaf commented
hi @mariaBer, please review the tutorial after my fixes.

Thanks.

2023-11-26 10:23 UTC, mariaBer commented on docs_tutorials/drone/drone.md
>  Then open the repository in VSCode's `devcontainer` with `reopen in container option`.
Agreed, we will need to add a link to "reopen in container" option

2023-11-26 10:30 UTC, mariaBer requested changes
Sorry for the delay..

2023-11-26 10:30 UTC, mariaBer commented on docs_tutorials/drone/drone.md
> +## Drone
# Drone

2023-11-26 10:30 UTC, mariaBer commented on docs_tutorials/drone/drone.md
>  Then open the repository in VSCode's `devcontainer` with `reopen in container option`.
`reopen in container` option.

Option is not part of the text

2023-11-26 10:30 UTC, mariaBer commented on docs_tutorials/drone/drone.md
> +1. Open the Drone project
Add link to citros.io as I mentioned in [this comment](https://github.com/lulav/citros_doc/pull/76#discussion_r1397618881)

2023-11-29 08:41 UTC, mariaBer commented
@iftahnaf, did you see I added a few new comments on the last update?

2023-11-29 20:21 UTC, iftahnaf commented on docs_tutorials/drone/drone.md
> +1. Open the Drone project
the link to citros.io will not work for users who are not members of the Lulav organization in citros.io

2023-11-29 20:22 UTC, iftahnaf commented
Hi @mariaBer, I update the tutorial according to your request.
Please review it.

2023-11-30 09:44 UTC, mariaBer commented on docs_tutorials/drone/drone.md
> +1. Open the Drone project
Yes it will.
Vova coded it in such way that the link will be the same regardless to the organization.
Meaning once you log in, it will open the project under your organization.

2023-11-30 19:34 UTC, iftahnaf commented
Hi @mariaBer, I added a link to the drone repository in CITROS.
Please review the tutorial.

Thanks!

2023-12-01 10:03 UTC, mariaBer approved these changes

2023-12-01 10:04 UTC, merged