doc(mass-spring-damper-tutorial): update
lulav/citros_doc pull request #77
Opened 2023-11-14 13:11 UTC by iftahnaf

hi @mariaBer,

I update the mass-spring-damper tutorial.

Please review.

2023-11-17 17:22 UTC, mariaBer requested changes

2023-11-17 17:22 UTC, mariaBer commented on docs_tutorials/mass_spring_damper/mass_spring_damper.md
Please review requested drone fixes, add then here as well. https://github.com/lulav/citros_doc/pull/76#pullrequestreview-1737421079

2023-11-17 17:22 UTC, mariaBer commented on docs_tutorials/mass_spring_damper/mass_spring_damper.md
Please change to composition of the fields to look like in drone (or update in drone to look like this)

| Parameter | Description | Package

2023-11-17 17:22 UTC, mariaBer commented on docs_tutorials/mass_spring_damper/mass_spring_damper.md
line 116 (https://citros.io/doc/docs/repos/repos_file_structure/repos_fs_param_setup). not exist

2023-11-19 11:39 UTC, iftahnaf commented
Hi @mariaBer, I fixes the issues, please review.

Thanks.

2023-11-26 10:48 UTC, mariaBer requested changes

2023-11-26 10:48 UTC, mariaBer commented on docs_tutorials/mass_spring_damper/mass_spring_damper.md
> +## Mass-Spring-Damper
# Mass-Spring-Damper

2023-11-26 10:48 UTC, mariaBer commented on docs_tutorials/mass_spring_damper/mass_spring_damper.md
> +5. [Running the scenario using CITROS](#running-the-scenario-using-citros)
Capitalise  - Running the Scenario Using CITROS

2023-11-26 10:48 UTC, mariaBer commented on docs_tutorials/mass_spring_damper/mass_spring_damper.md
> +## Running the scenario using CITROS
Capitalise  - Running the Scenario Using CITROS

2023-11-26 10:48 UTC, mariaBer commented on docs_tutorials/mass_spring_damper/mass_spring_damper.md
> +Then open the repository in VSCode's `devcontainer` with `reopen in container option`.
`reopen in container` option.

2023-11-29 08:41 UTC, mariaBer commented
@iftahnaf, did you see I added a few new comments on the last update?

2023-11-29 20:27 UTC, iftahnaf commented
Hi @mariaBer,  I update the tutorial according to your request.
Please review it.

2023-11-30 09:37 UTC, mariaBer approved these changes

2023-11-30 09:37 UTC, merged