docs (soft_landing):update
lulav/citros_doc pull request #78
Opened 2023-11-15 15:07 UTC by orrlulavspace

hi @mariaBer,

I updated the soft landing tutorial.

2023-11-26 11:55 UTC, mariaBer requested changes

2023-11-26 11:55 UTC, mariaBer commented on docs_tutorials/soft_landing/soft_landing.md
> +# [Soft Landing Tutorial]
remove []

2023-11-26 11:55 UTC, mariaBer commented on docs_tutorials/soft_landing/soft_landing.md
> +# Table of Contents
Change back to numbers

2023-11-27 08:10 UTC, orrlulavspace commented on docs_tutorials/soft_landing/soft_landing.md
> +**All of the above are ROS 2 parameters that could easily change by the user as wish [citros_cli](/docs_cli/configuration/config_params) provides more information about how to change the parameters.*
is there a problem with the link here?

2023-11-27 11:44 UTC, mariaBer requested changes

2023-11-27 11:44 UTC, mariaBer commented on docs_tutorials/soft_landing/soft_landing.md
> +**[citros_cli](/docs_cli/configuration/config_params) provides more information about how to change the parameters by the user.**
You can remove the highlight

2023-11-27 11:44 UTC, mariaBer commented on docs_tutorials/soft_landing/soft_landing.md
> +At the web, go to the [Runs tab](https://citros.io/soft_landing/batch) in the soft landing repo.
Go to [Runs tab](https://citros.io/soft_landing/batch) in your soft landing repo.

2023-11-27 11:44 UTC, mariaBer commented on docs_tutorials/soft_landing/soft_landing.md
> +Start a new simulation by clicking the `Run simulation` green button, and then a window will pop:
Open a new simulation configuration window by clicking the green `Run simulation` button.

2023-11-27 11:44 UTC, mariaBer commented on docs_tutorials/soft_landing/soft_landing.md
>  As you can see I chose to fill the soft landing repository, the main branch, and run the simulations with the controller.
As you can see, the dynamic controller simulation will run on the main branch in soft_landing repository.

2023-11-27 11:44 UTC, mariaBer commented on docs_tutorials/soft_landing/soft_landing.md
> +Then I chose to repeat 100 times such that CITROS run 10 simulations in parallel, that way I could get results much fester.
CITROS will run this simulation 100 times while in total while in each iteration, 10 of them will run in parallel, meaning the results will be received faster.

2023-11-27 11:44 UTC, mariaBer commented on docs_tutorials/soft_landing/soft_landing.md
> +The full report with the data access and error analysis using the data analysis package you can watch it [here](https://CITROS.io/soft_landing/blob/main/notebooks/Soft_landing_analysis.ipynb).
The full report with the data access and error analysis was generated using the data analysis package, can be found [here](https://CITROS.io/soft_landing/blob/main/notebooks/Soft_landing_analysis.ipynb).

2023-11-27 11:54 UTC, vovacooper commented on docs_tutorials/soft_landing/soft_landing.md
> +## Scenario
Describe the scenario, what your assumption, what you think you will achieve after you run this and get the results. this section is more like a "מעבדה", you sorta need to explain the hypothesis, the experiment and the results.

here you want to validate the controller (the hypothesis), but for the dumb of us. please give a few words on it, and how you want to validate it by this scenario. 
how many runs you need for this scenario? 10 is enough? 100? 1000?
is it a complete validation? is it a small part of a whole set of validations? 
in the result you will analyse the results of this scenario (experiment?)

2023-11-29 10:17 UTC, orrlulavspace commented
hey @mariaBer and @vovacooper i updated the tutorial

2023-11-29 10:46 UTC, mariaBer approved these changes

2023-11-29 10:46 UTC, merged