docs(docs_tutorials/gal_orbits): update according to the new template
lulav/citros_doc pull request #79
Opened 2023-11-16 08:27 UTC by Yalyalieva

I increased the number of '#' in section titles and left single '#' only near the main title of the page because the right sidebar do not count titles with one '#' so it did not show the content right.
I also added some subsections under the main sections of the template. I added titles of the subsections to the ToC but can remove them from there. If you do not want these subsections to be shown in the right sidebar and want only the main sections to be displayed, it also can be adjusted.

2023-11-26 11:17 UTC, mariaBer requested changes

2023-11-26 11:17 UTC, mariaBer commented on docs_tutorials/gal_orbits/gal_orbits.md
change srs/... to src/... in all places

2023-11-26 11:17 UTC, mariaBer commented on docs_tutorials/gal_orbits/gal_orbits.md
> +After adjusting [parameter](#parameter-setup) and [simulation](#simulation-setup) setups, you need to commit and push your changes and also build and push a docker image. To do this please continue f
To do this please follow the [Getting Started tutorial](https://citros.io/doc/docs_tutorials/getting_started/).

2023-11-26 11:17 UTC, mariaBer commented on docs_tutorials/gal_orbits/gal_orbits.md
> +Explore more ways of running scenarios on [Getting Started page](https://citros.io/doc/docs_tutorials/getting_started/).
which ways? 
maybe delete this line. if you insist leaving it, add example of which ways, change to [Getting Started tutorial] and send to aa specific location in the tutorial

2023-11-26 11:17 UTC, mariaBer commented on docs_tutorials/gal_orbits/gal_orbits.md
> +Now when your simulation is complete, you're ready to check the results! Explore the notebooks in [`citros_template/notebooks`](https://github.com/citros-garden/gal_orbits/tree/main/citros_template/n
link should take to the repo in citros.io https://citros.io/gal_orbits/tree/main/notebooks

2023-11-26 11:21 UTC, vovacooper requested changes

2023-11-26 11:21 UTC, vovacooper commented on docs_tutorials/gal_orbits/gal_orbits.md
> +The output of the simulation is an array of 11 variables:
output of the simulation sounds a bit off... its not like a function that we expect an output. 
we record all the topics of the robot, and this is out output. 
you definitely should explain the topics + the scheme + explain the values like you did.

2023-11-26 11:21 UTC, vovacooper commented on docs_tutorials/gal_orbits/gal_orbits.md
> +## Results
in the scenario section you explained what you are up to. 
in the result section you need to investigate your hypothesis suggested in the scenario section to show the power of CITROS.
what you wrote is very good but it is very generic and can go for all the tutorials.

please add after this what you are validating/verifying/what to know from the scenario.

2023-11-29 08:40 UTC, mariaBer commented
@Yalyalieva , me and Vova had a few comments on the last update

2023-11-29 14:28 UTC, Yalyalieva commented on docs_tutorials/gal_orbits/gal_orbits.md
> +Now when your simulation is complete, you're ready to check the results! Explore the notebooks in [`citros_template/notebooks`](https://github.com/citros-garden/gal_orbits/tree/main/citros_template/n
I changed the link but will the notebooks automatically be copied from the citros_template/notebooks to the .citros/notebooks folder when the project is created by user? Because I thought that the notebooks should be copied to .citros folder manually from the citros_template/notebooks.

2023-11-29 14:28 UTC, Yalyalieva commented on docs_tutorials/gal_orbits/gal_orbits.md
> +Explore more ways of running scenarios on [Getting Started page](https://citros.io/doc/docs_tutorials/getting_started/).
It was suggested in the template to make a link to getting started page. I think it is better to remove this line.

2023-11-29 14:29 UTC, Yalyalieva commented on docs_tutorials/gal_orbits/gal_orbits.md
> +The output of the simulation is an array of 11 variables:
I changed this sentence

2023-11-29 14:29 UTC, Yalyalieva commented on docs_tutorials/gal_orbits/gal_orbits.md
> +## Results
I added more analysis

2023-11-30 06:17 UTC, vovacooper approved these changes

2023-11-30 07:17 UTC, mariaBer commented on docs_tutorials/gal_orbits/gal_orbits.md
> +Now when your simulation is complete, you're ready to check the results! Explore the notebooks in [`citros_template/notebooks`](https://github.com/citros-garden/gal_orbits/tree/main/citros_template/n
Yes, they are created automatically.

Does the results section refers to a specific notebook? if so, please add the specific notebook (I see [3 notebooks](https://citros.io/gal_orbits/tree/main/notebooks) in the project) so the user would be able read and follow what you are showing here.

2023-11-30 09:34 UTC, Yalyalieva commented on docs_tutorials/gal_orbits/gal_orbits.md
> +Now when your simulation is complete, you're ready to check the results! Explore the notebooks in [`citros_template/notebooks`](https://github.com/citros-garden/gal_orbits/tree/main/citros_template/n
I updated notebooks and added link

2023-11-30 09:46 UTC, mariaBer approved these changes

2023-11-30 09:46 UTC, merged