docs(docs_tutorials/pendulum): tutorial for the pendulum project
lulav/citros_doc pull request #85
Opened 2023-12-03 09:32 UTC by Yalyalieva

Hi, here is the tutorial for the pendulum project

2023-12-06 08:53 UTC, mariaBer requested changes

2023-12-06 08:53 UTC, mariaBer commented on docs_tutorials/pendulum/Pendulum.md
> +Refer to the notebook [notebooks/double_pendulum.ipynb](https://citros.io/pendulum/blob/main/notebooks/double_pendulum.ipynb) for more detailed information about batches and additional ideas on visua
add <br /> at the end of the sentence so that next sentence will start in new line

2023-12-06 08:53 UTC, mariaBer commented on docs_tutorials/pendulum/Pendulum.md
> +Additionally, examine [notebooks/system_with_spring.ipynb](https://citros.io/pendulum/blob/main/notebooks/system_with_spring.ipynb) for a detailed view of behavior of the spring system.
for a detailed view of the spring system behavior.

2023-12-07 11:16 UTC, mariaBer commented on docs_tutorials/pendulum/Pendulum.md
> +Refer to the notebook [notebooks/double_pendulum.ipynb](https://citros.io/pendulum/blob/main/notebooks/double_pendulum.ipynb) for more detailed information about batches and additional ideas on visua
add "<br />" at the end of the sentence so that next sentence will start in new line
The above will just go to new link rather than a new paragraph

2023-12-07 11:21 UTC, mariaBer requested changes
I added a comment about tables re-order. I saw that the same order is in galactic tutorial as well. If you can update there as well

2023-12-07 11:21 UTC, mariaBer commented on docs_tutorials/pendulum/Pendulum.md
> +#### Double pendulum
Capitalise

2023-12-07 11:21 UTC, mariaBer commented on docs_tutorials/pendulum/Pendulum.md
> +#### System with spring
Capitalise

2023-12-07 11:21 UTC, mariaBer commented on docs_tutorials/pendulum/Pendulum.md
> +Parameter | Description | Default
Please change order so Parameter | Default | Description

2023-12-07 11:21 UTC, mariaBer commented on docs_tutorials/pendulum/Pendulum.md
> +Parameter | Description | Default
Please change order so Parameter | Default | Description

2023-12-07 11:41 UTC, Yalyalieva commented on docs_tutorials/pendulum/Pendulum.md
> +Refer to the notebook [notebooks/double_pendulum.ipynb](https://citros.io/pendulum/blob/main/notebooks/double_pendulum.ipynb) for more detailed information about batches and additional ideas on visua
Sorry, I don't understand after which sentence? I thought after

> Refer to the notebook [notebooks/double_pendulum.ipynb](https://citros.io/pendulum/blob/main/notebooks/double_pendulum.ipynb) for more detailed information about batches and additional ideas on visualization, such as plotting the animation of the pendulum's motion.

and I added a blank line after it so the next sentence:

> Additionally, examine [notebooks/system_with_spring.ipynb](https://citros.io/pendulum/blob/main/notebooks/system_with_spring.ipynb) for a detailed view of the spring system behavior.

goes with the new paragraph

2023-12-07 12:10 UTC, mariaBer commented on docs_tutorials/pendulum/Pendulum.md
> +Refer to the notebook [notebooks/double_pendulum.ipynb](https://citros.io/pendulum/blob/main/notebooks/double_pendulum.ipynb) for more detailed information about batches and additional ideas on visua
instead of new line, add a line break < br />  (with no spaces, like in image)
<img width="45" alt="image" src="https://github.com/lulav/citros_doc/assets/23418333/fba59ba8-8710-48a3-b521-989f66dfc0c0">

Then your text will start in a new line and not a new paragraph

Refer to the notebook [notebooks/double_pendulum.ipynb](https://citros.io/pendulum/blob/main/notebooks/double_pendulum.ipynb) for more detailed information about batches and additional ideas on visualization, such as plotting the animation of the pendulum's motion.<br /> Additionally, examine [notebooks/system_with_spring.ipynb](https://citros.io/pendulum/blob/main/notebooks/system_with_spring.ipynb) for a detailed view of the spring system behavior.

If it is still unclear, add the rest and I will update from my end

2023-12-07 12:27 UTC, Yalyalieva commented on docs_tutorials/pendulum/Pendulum.md
> +Refer to the notebook [notebooks/double_pendulum.ipynb](https://citros.io/pendulum/blob/main/notebooks/double_pendulum.ipynb) for more detailed information about batches and additional ideas on visua
ok, got it now, thanks

2023-12-07 12:41 UTC, merged