Tutorial update
lulav/citros_doc pull request #96
Opened 2023-12-15 11:25 UTC by gtep96

Requesting review

2023-12-18 14:13 UTC, mariaBer requested changes

2023-12-18 14:13 UTC, mariaBer commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +For this tutorial, let's check how far the Hopper can hop depending on Specific Impulse. The optimal trajectory computes by solving non-linear optimal control problems(OCP) in the standard Bolza form
more information about MPOPT optimal control solving library on the MPOPT GitHub or website.<br/> 
link to github and/or website

2023-12-18 14:13 UTC, mariaBer commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +For this tutorial, let's check how far the Hopper can hop depending on Specific Impulse. The optimal trajectory computes by solving non-linear optimal control problems(OCP) in the standard Bolza form
For this tutorial, let's check how far the Hopper can hop depending on Specific Impulse.
remove

2023-12-19 10:34 UTC, gtep96 commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +For this tutorial, let's check how far the Hopper can hop depending on Specific Impulse. The optimal trajectory computes by solving non-linear optimal control problems(OCP) in the standard Bolza form
Done

2023-12-19 10:35 UTC, gtep96 commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +For this tutorial, let's check how far the Hopper can hop depending on Specific Impulse. The optimal trajectory computes by solving non-linear optimal control problems(OCP) in the standard Bolza form
Done

2023-12-19 10:36 UTC, gtep96 commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +The main goal of the project is to find the optimal way to "hop" on the Moon as far as possible with given vessel parameters.<br/>
Done

2023-12-19 10:37 UTC, gtep96 commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +For this tutorial, let's check how far the Hopper can hop depending on Specific Impulse. The optimal trajectory computes by solving non-linear optimal control problems(OCP) in the standard Bolza form
Done

2023-12-19 10:39 UTC, gtep96 commented
@mariaBer updated and pushed

2023-12-19 19:08 UTC, mariaBer requested changes

2023-12-19 19:08 UTC, mariaBer commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +The default setup is 600 seconds timeout, 4 CPU, 4 GPU and 4096 MB of Memory.
Am I missing something?
![image](https://github.com/lulav/citros_doc/assets/23418333/d2a971f0-9ae9-4c6e-946b-1f4b4ec171cd)

2023-12-19 19:08 UTC, mariaBer commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +To plot the local run results you can use [Foxglove](https://citros.io/doc/docs_tutorials/#visualization-with-foxglove).
1. Should both of the layouts work? should one? add the relevant information
2. None of the layouts worked for me

2023-12-19 20:08 UTC, gtep96 commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +The default setup is 600 seconds timeout, 4 CPU, 4 GPU and 4096 MB of Memory.
@mariaBer https://github.com/lulav/citros_doc/pull/101#discussion_r1431885192

2023-12-20 12:26 UTC, gtep96 commented
updated and pushed

2023-12-20 17:13 UTC, mariaBer commented on docs_tutorials/lunar_hopper/lunar_hopper.md
> +To plot the local run results you can use [Foxglove](https://citros.io/doc/docs_tutorials/#visualization-with-foxglove).
If you mention foxglove, add one of the results foxglove gives

2023-12-21 09:58 UTC, gtep96 commented
updated and pushed

2023-12-21 10:53 UTC, merged