Robotic arm Tutorial update
lulav/citros_doc pull request #99
Opened 2023-12-15 11:26 UTC by gtep96

Requesting review

2023-12-17 08:55 UTC, mariaBer requested changes

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
>  For Forward Kinematic:
- Forward Kinematic simulation parameters:

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
>  For Inverse Kinematic:
- Inverse Kinematic simulation parameters:

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +This project contains two launch files: ```simulation_my_doosan_gazebo_controller``` for Forward Kinematic or ```simulation_inverse_kinematic_pkg``` for Inverse Kinematic. These files will be used fo
...Forward Kinematic and ```simulation_inverse_kinematic_pkg``` for ...

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +### Inverse kinematics
-

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +### Forward kinematics
-

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +### Forward kinematics
Explain as you explained the previous one, what it used for, what configuration, what is the result

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +This parameters can be found in ```.citros/simulations/simulation_my_doosan_gazebo_controller.json``` (for Forward Kinematic) or ```.citros/simulations/simulation_inverse_kinematic_pkg.json``` (for I
remove brackets

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +All the results will be saved under .citros/runs/[simulation_name] [folder].
All the results will be saved in `.citros/runs/[simulation_name]` folder.

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +Select the launch file by pressing ```Enter``` button and wait for the output in the terminal. To plot the local run results you can use FoxGlove.
Select the `simulation_my_doosan_gazebo_controller` by pressing ```Enter``` button and wait for the output in the terminal.

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +To plot the local run results you can use [FoxGlove](https://citros.io/doc/docs_tutorials/#visualization-with-foxglove).
- [ ] Foxglove
- [ ] ....with the ```layout.json``` layout that exists in the ```Foxglove_layouts``` directory.

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +Select the launch file by pressing `Enter` button. Now the simulation is running in the CITROS server, and the results will be automatically uploaded to the CITROS database.
Select the simulation_my_doosan_gazebo_controller by pressing Enter..

2023-12-17 08:55 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +>>> citros run -n 'robotic_arm' -m 'local test run'
error when running the simulation (either one)
![image](https://github.com/lulav/citros_doc/assets/23418333/013485b4-c3cb-4935-9a57-99c154409d17)

2023-12-17 09:20 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +4. (Optional) Install [FoxGlove](https://docs.foxglove.dev/docs/introduction).
Foxglove

2023-12-17 12:04 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
>  For Forward Kinematic:
Done

2023-12-17 12:04 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
>  For Inverse Kinematic:
Done

2023-12-17 12:05 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +This project contains two launch files: ```simulation_my_doosan_gazebo_controller``` for Forward Kinematic or ```simulation_inverse_kinematic_pkg``` for Inverse Kinematic. These files will be used fo
fixed

2023-12-17 12:05 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +### Inverse kinematics
Done

2023-12-17 12:05 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +### Forward kinematics
Done

2023-12-17 12:10 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +### Forward kinematics
Done

2023-12-17 12:11 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +This parameters can be found in ```.citros/simulations/simulation_my_doosan_gazebo_controller.json``` (for Forward Kinematic) or ```.citros/simulations/simulation_inverse_kinematic_pkg.json``` (for I
Done

2023-12-17 12:11 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +All the results will be saved under .citros/runs/[simulation_name] [folder].
Done

2023-12-17 12:12 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +Select the launch file by pressing ```Enter``` button and wait for the output in the terminal. To plot the local run results you can use FoxGlove.
Done

2023-12-17 12:13 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +To plot the local run results you can use [FoxGlove](https://citros.io/doc/docs_tutorials/#visualization-with-foxglove).
Done

2023-12-17 12:13 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +Select the launch file by pressing `Enter` button. Now the simulation is running in the CITROS server, and the results will be automatically uploaded to the CITROS database.
Done

2023-12-17 12:13 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +>>> citros run -n 'robotic_arm' -m 'local test run'
CITROS error

2023-12-17 12:13 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +4. (Optional) Install [FoxGlove](https://docs.foxglove.dev/docs/introduction).
Done

2023-12-17 12:14 UTC, gtep96 commented
@mariaBer done, changes pushed

2023-12-18 06:37 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +This project contains two launch files: ```simulation_my_doosan_gazebo_controller``` for Forward Kinematic or ```simulation_inverse_kinematic_pkg``` for Inverse Kinematic. These files will be used fo
Actually - This project contains two launch files: is enough since all the rest is written in the table
will be added to the updated review

2023-12-18 06:38 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +This project contains two launch files: ```simulation_my_doosan_gazebo_controller``` for Forward Kinematic and ```simulation_inverse_kinematic_pkg``` for Inverse Kinematic. These files will be used f
This project contains two launch files:
(remove the rest)

2023-12-18 06:38 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +### Forward kinematics
need to add a new line, same format as in poliastro!
will be added to the updated review

2023-12-18 06:38 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +### Inverse kinematics
need to add a new line, same format as in poliastro!
will be added to the updated review

2023-12-18 06:53 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +* Inverse kinematics
br at the end

2023-12-18 06:53 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +* Forward kinematics
br at the end

2023-12-18 06:53 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +    Forward Kinematic calculation is the simplest way to control the robotic arm behaviour. User provides joints target positions as input parameters to configure the simulation. The robotic arm will
if you added br before user provide... in the previous point, do the same here. the format should be the same

2023-12-18 06:53 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +    For this example, let's check how the robotic arm's behavior changes depending on target position. To find it out, we need to set up parameters and launch CITROS simulation.<br/>
rewrite the text from this point until the json code.
instead of two separate sentences it should be a fluid paragraph. It doesn't make sense that you writing to find it out.... and then again to find out...
add the function text you have below the example to be a part of this paragraph

2023-12-18 06:53 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +All the results will be saved in .citros/runs/[simulation_name] folder.
`.citros/runs/[simulation_name]`

2023-12-18 06:53 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +Select the ```simulation_my_doosan_gazebo_controller``` launch file by pressing ```Enter``` button and wait for the output in the terminal.
file by pressing ---> and press

2023-12-18 06:53 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +All the results will be saved under .citros/runs/[simulation_name] [folder].
Not done
added to review

2023-12-18 07:12 UTC, mariaBer requested changes

2023-12-18 07:12 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
- [ ] There are two simulations, shouldn't there be two foxglove layouts?
- [ ] Is the existing layout relevant for both simulations? 
- [ ] rename the layout to something less generic than layout.json. if the layout relevant only for the specific simulation, rename to the simulation name

2023-12-18 11:43 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +This project contains two launch files: ```simulation_my_doosan_gazebo_controller``` for Forward Kinematic and ```simulation_inverse_kinematic_pkg``` for Inverse Kinematic. These files will be used f
Done

2023-12-18 11:43 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +* Forward kinematics
Done

2023-12-18 11:43 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +    Forward Kinematic calculation is the simplest way to control the robotic arm behaviour. User provides joints target positions as input parameters to configure the simulation. The robotic arm will
Done

2023-12-18 11:47 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +    For this example, let's check how the robotic arm's behavior changes depending on target position. To find it out, we need to set up parameters and launch CITROS simulation.<br/>
Like this?

* Forward kinematics <br/>
    Forward Kinematic calculation is the simplest way to control the robotic arm behaviour. <br/> 
    User provides joints target positions as input parameters to configure the simulation. The robotic arm will change its position trying to meet the target conditions, and the simulation publishes the current positions of joints as a result.<br/>
    For this example, let's check how the robotic arm's behavior changes depending on target position. To find it out, we need to launch a batch with several simulations and a distribution for the last joint position parameter, it will be set by a NumPy random function. <br/>
    The parameter setup is listed in ```.citros/parameter_setups/default_param_setup.json```: <br/>

2023-12-18 11:48 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +    For this example, let's check how the robotic arm's behavior changes depending on target position. To find it out, we need to set up parameters and launch CITROS simulation.<br/>
The function goes right after it. Is it ok?

2023-12-18 11:49 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +All the results will be saved in .citros/runs/[simulation_name] folder.
Done

2023-12-18 11:50 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +Select the ```simulation_my_doosan_gazebo_controller``` launch file by pressing ```Enter``` button and wait for the output in the terminal.
Done

2023-12-18 11:50 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +Select the ```simulation_my_doosan_gazebo_controller``` launch file by pressing `Enter` button. Now the simulation is running in the CITROS server, and the results will be automatically uploaded to t
Done

2023-12-18 11:53 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
The layout is relevant for both of the simulations. Is the renaming necessary in this case?

2023-12-18 11:55 UTC, gtep96 commented
Done and pushed

2023-12-20 07:16 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +    For this example, let's check how the robotic arm's behavior changes depending on target position. To find it out, we need to launch a batch with several simulations and a distribution for the la
In this tutorial, let's check how the robotic arm's behavior changes depending on target position. <br />
    For that, we will launch a batch simulation with a random distribution ranging between 0.0 and 0.5, for the last joint position parameter  (`j5`).
    The parameter will be set by a NumPy random function and its  setup is listed in ```.citros/parameter_setups/default_param_setup.json```: <br/>

2023-12-20 07:16 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +This function will set the ```j5``` parameter in random range from 0.0 to 0.5.
remove

2023-12-20 07:16 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
> +    For this example, let's check how the robotic arm's behavior changes depending on target position. To find it out, we need to set up parameters and launch CITROS simulation.<br/>
I added a rewrite in the new review

2023-12-20 07:17 UTC, mariaBer commented on docs_tutorials/robotic_arm/robotic_arm.md
No need

2023-12-20 12:29 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +    For this example, let's check how the robotic arm's behavior changes depending on target position. To find it out, we need to launch a batch with several simulations and a distribution for the la
Done

2023-12-20 12:29 UTC, gtep96 commented on docs_tutorials/robotic_arm/robotic_arm.md
> +This function will set the ```j5``` parameter in random range from 0.0 to 0.5.
Done

2023-12-20 12:29 UTC, gtep96 commented
updated and pushed

2023-12-20 17:31 UTC, mariaBer commented
Did you check why you have a colorful foxglove result and I get everything in blue?

2023-12-21 09:22 UTC, gtep96 commented
> Did you check why you have a colorful foxglove result and I get everything in blue?

Yes, pull the changes from the project's repo and check it. Now it should be colorful

2023-12-21 09:33 UTC, mariaBer approved these changes

2023-12-21 09:33 UTC, merged